import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const chrome=readFileSync(new URL('../dist/interface/reading-chrome.js',import.meta.url),'utf8');
const position=readFileSync(new URL('../dist/interface/reading-position.js',import.meta.url),'utf8');
const messages={},frames=[{},{}],book={dataset:{view:'people'},querySelectorAll:()=>leaves};
const leaves=['people','ingredients'].map((id,i)=>({id,querySelector:()=>({contentWindow:frames[i]})}));
let changed;const footer={hidden:true,contains:()=>false,addEventListener(){}};
vm.runInNewContext('const book="existing shell"; const leaves=[];'+chrome,{document:{querySelector:s=>s==='.book'?book:footer},location:{origin:'https://example.test'},window:{addEventListener:(name,fn)=>messages[name]=fn},MutationObserver:class{constructor(fn){changed=fn}observe(){}},queueMicrotask:fn=>fn()});
const send=(source,nearBottom,origin='https://example.test')=>messages.message({source,origin,data:{type:'book-reading-position',nearBottom}});
send(frames[0],true,'https://wrong.test');assert.equal(footer.hidden,true);
send({},true);assert.equal(footer.hidden,true);
send(frames[1],true);assert.equal(footer.hidden,true,'A folded pane cannot reveal the footer');
send(frames[0],true);assert.equal(footer.hidden,false);
send(frames[0],false);assert.equal(footer.hidden,true);
book.dataset.view='ingredients';changed();assert.equal(footer.hidden,false);
book.dataset.view='together';changed();assert.equal(footer.hidden,false);
const events={},reports=[],root={scrollTop:0,scrollHeight:3000};
vm.runInNewContext(position,{document:{documentElement:{classList:{contains:()=>true}},scrollingElement:root,body:{}},innerHeight:800,location:{origin:'https://example.test'},parent:{postMessage:m=>reports.push(m)},window:{addEventListener:(name,fn)=>events[name]=fn},ResizeObserver:class{observe(){}},requestAnimationFrame:fn=>fn()});
assert.equal(reports.at(-1).nearBottom,false);
root.scrollTop=1950;events.scroll();assert.equal(reports.at(-1).nearBottom,true);
root.scrollTop=1800;events.resize();assert.equal(reports.at(-1).nearBottom,true,'A footer-height change must not cause flicker');
root.scrollTop=1600;events.scroll();assert.equal(reports.at(-1).nearBottom,false);
root.scrollTop=0;events.scroll();assert.equal(reports.at(-1).nearBottom,false);
console.log('PASS: footer follows visible panes, rejects untrusted messages, and reveals near the bottom without flicker.');
