import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH || 'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const base=process.env.TEST_URL || 'http://127.0.0.1:8774';
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base+'/notes/ingredients/techniques.html');
 await page.waitForSelector('body[data-provenance="ready"][data-portraits="ready"]');
 assert.equal(await page.locator('.tile .people-preview').count(),40,'Every existing technique must expose its human ingredients');
 await page.locator('.tile').first().click();
 await page.waitForSelector('#human-ingredients .ingredient-person');
 assert.match(await page.locator('#human-ingredients').innerText(),/Robert Bridson/);
 assert.match(await page.locator('#human-ingredients').innerText(),/Jim Hourihan/);
 assert.match(await page.locator('#human-ingredients').innerText(),/Marcus Nordenstam/);
 assert.ok(await page.locator('#human-ingredients a.evidence-link').count()>=3);
 assert.ok(await page.locator('#human-ingredients img').count()>0,'Provenance must include faces');
 await page.locator('#next').click();
 await page.waitForFunction(()=>document.querySelector('#human-ingredients')?.dataset.technique==='Domain warping');
 assert.match(await page.locator('#human-ingredients').innerText(),/Ken Perlin/);
 assert.equal(await page.locator('#human-ingredients img[data-person="Ken Perlin"]').getAttribute('src'),'/notes/living/portraits/perlin.png','Reuse existing assets');
 await page.locator('#close').click();
 await page.locator('#people-search').fill('Perlin');
 assert.ok(await page.locator('.tile:visible').count()>0);
 assert.ok(await page.locator('.tile:visible').count()<40);
 await page.locator('#people-search').fill('NoPersonWithThisName');
 assert.equal(await page.locator('.tile:visible').count(),0);
 assert.equal(await page.locator('#recipe-empty').isVisible(),true);
 await page.locator('#people-search').fill('');
 assert.equal(await page.locator('.tile:visible').count(),40);
 await page.getByRole('button',{name:'Signal & interference',exact:true}).click();
 assert.equal(await page.locator('.tile:visible').count(),3);
 await page.locator('.tile:visible').first().click();
 assert.match(await page.locator('#detail-title').innerText(),/Moiré/);
 assert.equal(await page.locator('#human-ingredients').getAttribute('data-technique'),'Moiré');
 await page.setViewportSize({width:320,height:740});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.equal(await page.locator('#detail').evaluate(el=>el.scrollWidth>el.clientWidth),false);
 await page.locator('#detail').evaluate(el=>el.scrollTop=el.scrollHeight);
 await page.locator('#next').click();
 await page.waitForTimeout(50);
 assert.equal(await page.locator('#detail').evaluate(el=>el.scrollTop),0,'Next recipe starts at the top');
 await page.keyboard.press('Escape');
 await page.route('**/portrait-map.json',route=>route.abort());
 await page.goto(base+'/notes/ingredients/techniques.html');
 await page.waitForSelector('body[data-provenance=ready]');
 assert.equal(await page.locator('.people-preview').count(),40,'Missing portraits must not block human provenance');
 await page.unroute('**/portrait-map.json');
 await page.route('**/portrait-map.json',()=>{});
 await page.goto(base+'/notes/ingredients/techniques.html');
 await page.waitForSelector('body[data-provenance=ready]',{timeout:3000});
 assert.equal(await page.locator('.people-preview').count(),40,'Stalled portraits must not block human provenance');
 assert.deepEqual(errors,[]);
 console.log('PASS: all 40 food labels, named coauthors, source links, portrait reuse, navigation, person search, family filtering and phone layout.');
}finally{await browser.close()}
