import assert from 'node:assert/strict';
import {buildSkin} from '../dist/iterations/ultraviolet-best/skin.js';
import {articulate,swim,angleDelta,LENGTH} from '../dist/iterations/ultraviolet-best/body.js';
function fish(w=1280,h=720){const e={x:w*.5,y:h*.5,w,h,heading:0,speed:56,vx:56,vy:0,phase:0,requestedSpeed:108,navBounds:{left:45,right:w-45,top:45,bottom:h-45}};articulate(e,0);return e;}
for(const [w,h] of [[1280,720],[390,844]]){const e=fish(w,h);let maxYaw=0,maxJoint=0,minEdge=1e9,minSkin=1e9;for(let i=0;i<12000;i++){const goals=[[w-30,30],[30,h-30],[w-30,h-30],[30,30],[w/2,h/2]],g=goals[Math.floor(i/360)%5];e.target={x:g[0],y:g[1]};e.requestedSpeed=i%1800>1500?0:i%900>450?108:56;const a=e.heading,x=e.x,y=e.y,s=e.speed,oldYaw=e.yaw||0;swim(e,1/60);articulate(e,1/60);assert(Math.abs((e.yaw||0)-oldYaw)<=3/60+1e-8,'bounded angular acceleration');const yaw=Math.abs(angleDelta(e.heading,a))*60;maxYaw=Math.max(maxYaw,yaw);assert(yaw<=1.50001);assert(yaw<=Math.max(s,e.speed)/(70*Math.min(1,e.w/600,e.h/600))+1e-6,'minimum radius');assert(Math.abs(e.speed-s)<=160/60+1e-6);assert(Math.hypot(e.x-x,e.y-y)<=Math.max(s,e.speed)/60+1e-6,'no position teleport');assert(Math.abs(angleDelta(e.heading,e.body[1].a))<1e-8,'skull joins neck');for(let j=1;j<15;j++){assert(Math.abs(Math.hypot(e.body[j].x-e.body[j-1].x,e.body[j].y-e.body[j-1].y)-e.segmentLength)<1e-8,'fixed segment');const d=Math.abs(angleDelta(e.angles[j],e.angles[j-1]));maxJoint=Math.max(maxJoint,d);assert(d<=.180001,'no joint kink');}for(let j=6;j<15;j++)assert(Math.hypot(e.body[j].x-e.x,e.body[j].y-e.y)>j*e.segmentLength*.6,'no self fold');assert((e.turnLedger?.used||0)<=5*Math.PI+1e-9,'directional turn ceiling survives speed changes');const box=buildSkin(e).bounds;minSkin=Math.min(minSkin,box.left,w-box.right,box.top,h-box.bottom);minEdge=Math.min(minEdge,e.x,w-e.x,e.y,h-e.y);assert(e.x>15&&e.x<w-15&&e.y>15&&e.y<h-15,JSON.stringify({message:'head stays in tank',i,x:e.x,y:e.y,heading:e.heading,yaw:e.yaw,ledger:e.turnLedger,wall:e.wallTurn,escaping:e.escaping}));}console.log({w,h,maxYaw,maxJoint,minEdge,minSkin});assert(minSkin>=0,"whole fish stays in tank");}
const stopped=fish();stopped.speed=0;stopped.requestedSpeed=0;stopped.target={x:0,y:0};const a=stopped.heading;for(let i=0;i<60;i++){swim(stopped,1/60);articulate(stopped,1/60);}assert.equal(stopped.heading,a,'no swivel in place');
console.log('Ultraviolet body: 400 seconds of corner turns, reversals, speed changes and stops passed.');
// Reproduce V6's actual defect: low-speed reversal decouples the head and neck,
// and the added positional wave changes rendered link spacing.
const {Koi:Legacy}=await import('../dist/iterations/ultraviolet/koi.js');
globalThis.scrollY=0;
const old=Object.create(Legacy.prototype);Object.assign(old,{x:500,y:400,w:1280,h:720,right:1280,bottom:700,allType:true,heading:0,vx:56,vy:0,speed:56,phase:0,requestedSpeed:56,target:{x:100,y:400},spine:Array.from({length:15},(_,i)=>({x:500-i*6.4,y:400}))});
let neckError=0,linkError=0;
for(let i=0;i<120;i++){old.steer(1/60);old.articulate(1/60);neckError=Math.max(neckError,Math.abs(angleDelta(old.heading,old.body[1].a)));for(let j=1;j<15;j++)linkError=Math.max(linkError,Math.abs(Math.hypot(old.body[j].x-old.body[j-1].x,old.body[j].y-old.body[j-1].y)-6.4));}
assert(neckError>.3&&linkError>.2,'Regression reproduces the original independent-head and spacing defects');
console.log({legacyMaxHeadNeckDegrees:neckError*180/Math.PI,legacyMaxLinkError:linkError});
